### ISSUE TITLE
Bot log spam

### ISSUE THREAD

**Issue by androidacy-user** [AvinashReddy3108/PaperplaneExtended#14]
Something about filters is broken with the recent update

https://del.dog/adecawikoq

**Comment by AvinashReddy3108** [comment]
@alexa-v2 Yeah, we need to reset the SQL database due to reworked helpers.

**Comment by AvinashReddy3108** [comment]
@alexa-v2 How to reset your Heroku Postgres DB ?

- Turn off the dyno of the userbot, to avoid log spam.
- Open your Heroku app page.
- In the page where the Dyno switch lies, click on the Heroku Postgres addon link, it opens up a new page.
- In that page, open up the addon's Settings and click on Reset Database.
- Follow the instructions and wait for a few minutes before turning on the dyno again.

**Comment by androidacy-user** [comment]
@AvinashReddy3108 And lose EVERYTHING
