### ISSUE TITLE
Couple more bugs

### ISSUE THREAD

**Issue by androidacy-user** [AvinashReddy3108/PaperplaneExtended#17]
**Describe the bug**
https://del.dog/userbotscrewed.sql
https://del.dog/alalivihaz.cs

**To Reproduce**
1. Use the bot

**Expected behavior**
Anything else? 

**Screenshots**

**Python Version**
3.6.8

**Additional context**
Running in Docker

**Comment by AvinashReddy3108** [comment]
Did you not reset the db as recommended ?

**Comment by androidacy-user** [comment]
Of course I did. Didn't we go over the process of creating a new one? I assure you that I did not do that just for fun

**Comment by androidacy-user** [comment]
With new updates the issue is fixed but `.setwelcome` is nonfunctional
