### ISSUE TITLE
gdrive folder upload bug

### ISSUE THREAD

**Issue by masterzilla123** [AvinashReddy3108/PaperplaneExtended#24]
**Describe the bug**
.ggd command upload files & folder separately

**To Reproduce**
1. try to upload folder using .ggd command
2. check folder link & drive upload directory

**Expected behavior**
Empty folder created & upload files separately (outside created folder)

**Screenshots**
![image](https://user-images.githubusercontent.com/54639701/65747572-4e7bff00-e0f1-11e9-9590-daae65d2e56c.png)

![image](https://user-images.githubusercontent.com/54639701/65747593-5b98ee00-e0f1-11e9-8421-1bd77d9f83cd.png)

**Python Version**
3.7.4

**Additional context**

**Comment by AvinashReddy3108** [comment]
I see, would need to clean up and rewrite the stuff.
Thanks for letting me know.

**Comment by AvinashReddy3108** [comment]
This should be fixed with the recent update, do re-open this if not fixed.
