### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sweetcock69** [AvinashReddy3108/PaperplaneExtended#41]
After pressing deploy to heroku it's showing 

No app.json located in the repo URL provided.

Make sure that an app.json file exists in the project root directory.
![Screenshot_20191215-023102](https://user-images.githubusercontent.com/50311435/70854518-f8924880-1ee2-11ea-92cc-77b5b09d5c44.jpg)

**Comment by sweetcock69** [comment]
After deploy branch on heroku getting this error


=== Fetching app code
=== Building worker (Dockerfile)
Sending build context to Docker daemon  465.4kBStep 1/10 : FROM alpine:edge
edge: Pulling from library/alpine
8c15e203d0eb: Pulling fs layer
8c15e203d0eb: Verifying Checksum
8c15e203d0eb: Download complete
8c15e203d0eb: Pull complete
Digest: sha256:2f0fcd44f200bb1c0ddaed7370f042e66df1b7106c081285ad894e2fb9ba5bd2
Status: Downloaded newer image for alpine:edge
 ---> 60d63d8e1431
Step 2/10 : RUN sed -e 's;^#http\(.*\)/edge/community;http\1/edge/community;g' -i /etc/apk/repositories
 ---> Running in 811158ecdc32
Removing intermediate container 811158ecdc32
 ---> 768252d1be6d
Step 3/10 : RUN apk add --no-cache --update     bash     build-base     bzip2-dev     curl     figlet     gcc     g++     git     sudo     aria2     util-linux     libevent     chromium     chromium-chromedriver     jpeg-dev     libffi-dev     libpq     libwebp-dev     libxml2     libxml2-dev     libxslt-dev     linux-headers     musl     neofetch     openssl-dev     postgresql     postgresql-client     postgresql-dev     openssl     pv     jq     wget     python     python3     python3-dev     readline-dev     sqlite     ffmpeg     sqlite-dev     sudo     zlib-dev     jpeg-dev     python-dev
 ---> Running in e3c1dc5e5467
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
(1/172) Installing ca-certificates (20190108-r0)
(2/172) Installing c-ares (1.15.0-r0)
(3/172) Installing expat (2.2.9-r0)
(4/172) Installing libgcc (9.2.0-r3)
(5/172) Installing gmp (6.1.2-r1)
(6/172) Installing nettle (3.5.1-r0)
(7/172) Installing libffi (3.2.1-r6)
(8/172) Installing p11-kit (0.23.18.1-r0)
(9/172) Installing libtasn1 (4.15.0-r0)
(10/172) Installing libunistring (0.9.10-r0)
(11/172) Installing gnutls (3.6.10-r0)
(12/172) Installing sqlite-libs (3.30.1-r0)
(13/172) Installing libstdc++ (9.2.0-r3)
(14/172) Installing aria2 (1.35.0-r0)
(15/172) Installing ncurses-terminfo-base (6.1_p20191130-r0)
(16/172) Installing ncurses-terminfo (6.1_p20191130-r0)
(17/172) Installing ncurses-libs (6.1_p20191130-r0)
(18/172) Installing readline (8.0.1-r0)
(19/172) Installing bash (5.0.11-r1)
Executing bash-5.0.11-r1.post-install
(20/172) Installing binutils (2.33.1-r0)
(21/172) Installing libmagic (5.37-r1)
(22/172) Installing file (5.37-r1)
(23/172) Installing isl (0.18-r0)
(24/172) Installing libgomp (9.2.0-r3)
(25/172) Installing libatomic (9.2.0-r3)
(26/172) Installing mpfr4 (4.0.2-r1)
(27/172) Installing mpc1 (1.1.0-r1)
(28/172) Installing gcc (9.2.0-r3)
(29/172) Installing musl-dev (1.1.24-r0)
(30/172) Installing libc-dev (0.7.2-r0)
(31/172) Installing g++ (9.2.0-r3)
(32/172) Installing make (4.2.1-r2)
(33/172) Installing fortify-headers (1.1-r0)
(34/172) Installing build-base (0.5-r1)
(35/172) Installing libbz2 (1.0.8-r1)
(36/172) Installing bzip2-dev (1.0.8-r1)
(37/172) Installing eudev-libs (3.2.9-r1)
(38/172) Installing libpng (1.6.37-r1)
(39/172) Installing freetype (2.10.1-r0)
(40/172) Installing libuuid (2.34-r1)
(41/172) Installing fontconfig (2.13.1-r2)
(42/172) Installing libfontenc (1.1.4-r0)
(43/172) Installing mkfontscale (1.2.1-r1)
(44/172) Installing ttf-opensans (1.10-r0)
Executing ttf-opensans-1.10-r0.post-install
(45/172) Installing libogg (1.3.4-r0)
(46/172) Installing flac (1.3.3-r0)
(47/172) Installing libxau (1.0.9-r0)
(48/172) Installing libbsd (0.10.0-r0)
(49/172) Installing libxdmcp (1.1.3-r0)
(50/172) Installing libxcb (1.13.1-r0)
(51/172) Installing libx11 (1.6.9-r0)
(52/172) Installing libxcomposite (0.4.5-r0)
(53/172) Installing libxfixes (5.0.3-r2)
(54/172) Installing libxrender (0.9.10-r3)
(55/172) Installing libxcursor (1.2.0-r0)
(56/172) Installing libxdamage (1.1.5-r0)
(57/172) Installing libxext (1.3.4-r0)
(58/172) Installing libxi (1.7.10-r0)
(59/172) Installing libxrandr (1.5.2-r0)
(60/172) Installing libxscrnsaver (1.2.3-r0)
(61/172) Installing libxtst (1.2.3-r3)
(62/172) Installing alsa-lib (1.2.1.2-r0)
(63/172) Installing libintl (0.20.1-r2)
(64/172) Installing libblkid (2.34-r1)
(65/172) Installing libmount (2.34-r1)
(66/172) Installing pcre (8.43-r0)
(67/172) Installing glib (2.62.3-r0)
(68/172) Installing atk (2.34.1-r0)
(69/172) Installing dbus-libs (1.12.16-r2)
(70/172) Installing at-spi2-core (2.34.0-r0)
(71/172) Installing at-spi2-atk (2.34.1-r0)
(72/172) Installing sdl2 (2.0.10-r0)
(73/172) Installing fribidi (1.0.8-r0)
(74/172) Installing libass (0.14.0-r0)
(75/172) Installing lame (3.100-r0)
(76/172) Installing opus (1.3.1-r0)
(77/172) Installing libtheora (1.1.1-r14)
(78/172) Installing libjpeg-turbo (2.0.3-r0)
(79/172) Installing v4l-utils-libs (1.18.0-r0)
(80/172) Installing libpciaccess (0.16-r0)
(81/172) Installing libdrm (2.4.100-r0)
(82/172) Installing wayland-libs-client (1.17.0-r0)
(83/172) Installing libva (2.6.0-r0)
(84/172) Installing libvdpau (1.3-r0)
(85/172) Installing libvorbis (1.3.6-r2)
(86/172) Installing libvpx (1.8.1-r0)
(87/172) Installing x264-libs (20191119-r0)
(88/172) Installing x265-libs (3.2.1-r0)
(89/172) Installing xvidcore (1.3.5-r0)
(90/172) Installing ffmpeg-libs (4.2.1-r3)
(91/172) Installing pixman (0.38.4-r0)
(92/172) Installing cairo (1.16.0-r2)
(93/172) Installing avahi-libs (0.7-r4)
(94/172) Installing cups-libs (2.2.12-r1)
(95/172) Installing libevent (2.1.11-r0)
(96/172) Installing pkgconf (1.6.3-r0)
(97/172) Installing xz-libs (5.2.4-r0)
(98/172) Installing libxml2 (2.9.10-r1)
(99/172) Installing shared-mime-info (1.15-r0)
(100/172) Installing hicolor-icon-theme (0.17-r1)
(101/172) Installing tiff (4.1.0-r0)
(102/172) Installing gdk-pixbuf (2.40.0-r0)
(103/172) Installing gtk-update-icon-cache (2.24.32-r1)
(104/172) Installing libxinerama (1.1.4-r1)
(105/172) Installing cairo-gobject (1.16.0-r2)
(106/172) Installing libepoxy (1.5.4-r0)
(107/172) Installing graphite2 (1.3.13-r1)
(108/172) Installing harfbuzz (2.6.4-r0)
(109/172) Installing libxft (2.3.3-r0)
(110/172) Installing pango (1.44.7-r0)
(111/172) Installing wayland-libs-cursor (1.17.0-r0)
(112/172) Installing wayland-libs-egl (1.17.0-r0)
(113/172) Installing libxkbcommon (0.9.1-r0)
(114/172) Installing gtk+3.0 (3.24.13-r0)
Executing gtk+3.0-3.24.13-r0.post-install
(115/172) Installing nspr (4.24-r0)
(116/172) Installing nss (3.48-r0)
(117/172) Installing re2 (2019.12.01-r0)
(118/172) Installing snappy (1.1.7-r1)
(119/172) Installing libwebp (1.0.3-r0)
(120/172) Installing libgpg-error (1.36-r2)
(121/172) Installing libgcrypt (1.8.5-r0)
(122/172) Installing libxslt (1.1.34-r0)
(123/172) Installing chromium (78.0.3904.108-r0)
(124/172) Installing chromium-chromedriver (78.0.3904.108-r0)
(125/172) Installing nghttp2-libs (1.40.0-r0)
(126/172) Installing libcurl (7.67.0-r0)
(127/172) Installing curl (7.67.0-r0)
(128/172) Installing ffmpeg (4.2.1-r3)
(129/172) Installing figlet (2.2.5-r0)
(130/172) Installing pcre2 (10.34-r0)
(131/172) Installing git (2.24.1-r0)
(132/172) Installing libjpeg-turbo-dev (2.0.3-r0)
(133/172) Installing jpeg-dev (8-r6)
(134/172) Installing oniguruma (6.9.4-r0)
(135/172) Installing jq (1.6-r0)
(136/172) Installing linux-headers (4.19.36-r0)
(137/172) Installing libffi-dev (3.2.1-r6)
(138/172) Installing db (5.3.28-r1)
(139/172) Installing libsasl (2.1.27-r4)
(140/172) Installing libldap (2.4.48-r1)
(141/172) Installing libpq (12.1-r0)
(142/172) Installing libwebp-dev (1.0.3-r0)
(143/172) Installing zlib-dev (1.2.11-r3)
(144/172) Installing xz-dev (5.2.4-r0)
(145/172) Installing libxml2-dev (2.9.10-r1)
(146/172) Installing libxslt-dev (1.1.34-r0)
(147/172) Installing neofetch (6.1.0-r0)
(148/172) Installing openssl (1.1.1d-r2)
(149/172) Installing openssl-dev (1.1.1d-r2)
(150/172) Installing libedit (20191211.3.1-r0)
(151/172) Installing postgresql-client (12.1-r0)
(152/172) Installing tzdata (2019c-r0)
(153/172) Installing postgresql (12.1-r0)
Executing postgresql-12.1-r0.pre-install
(154/172) Installing postgresql-libs (12.1-r0)
(155/172) Installing postgresql-dev (12.1-r0)
(156/172) Installing pv (1.6.6-r1)
(157/172) Installing gdbm (1.13-r1)
(158/172) Installing python2 (2.7.16-r3)
(159/172) Installing python2-dev (2.7.16-r3)
(160/172) Installing python3 (3.8.0-r0)
(161/172) Installing python3-dev (3.8.0-r0)
(162/172) Installing libhistory (8.0.1-r0)
(163/172) Installing ncurses-dev (6.1_p20191130-r0)
(164/172) Installing readline-dev (8.0.1-r0)
(165/172) Installing sqlite (3.30.1-r0)
(166/172) Installing sqlite-dev (3.30.1-r0)
(167/172) Installing sudo (1.8.29-r0)
(168/172) Installing libsmartcols (2.34-r1)
(169/172) Installing findmnt (2.34-r1)
(170/172) Installing libfdisk (2.34-r1)
(171/172) Installing util-linux (2.34-r1)
(172/172) Installing wget (1.20.3-r0)
Executing busybox-1.31.1-r0.trigger
Executing ca-certificates-20190108-r0.trigger
Executing fontconfig-2.13.1-r2.trigger
Executing mkfontscale-1.2.1-r1.trigger
Executing glib-2.62.3-r0.trigger
Executing shared-mime-info-1.15-r0.trigger
Executing gdk-pixbuf-2.40.0-r0.trigger
Executing gtk-update-icon-cache-2.24.32-r1.trigger
OK: 745 MiB in 186 packages
Removing intermediate container e3c1dc5e5467
 ---> 53c426e93462
Step 4/10 : RUN python3 -m ensurepip     && pip3 install --upgrade pip setuptools     && rm -r /usr/lib/python*/ensurepip &&     if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi &&     if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi &&     rm -r /root/.cache
 ---> Running in af5738684a3e
Looking in links: /tmp/tmpq_trvig4
Requirement already satisfied: setuptools in /usr/lib/python3.8/site-packages (41.2.0)
Requirement already satisfied: pip in /usr/lib/python3.8/site-packages (19.2.3)
Collecting pip
  Downloading https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl (1.4MB)
  Collecting setuptools
    Downloading https://files.pythonhosted.org/packages/54/28/c45d8b54c1339f9644b87663945e54a8503cfef59cf0f65b3ff5dd17cf64/setuptools-42.0.2-py2.py3-none-any.whl (583kB)
    Installing collected packages: pip, setuptools
      Found existing installation: pip 19.2.3
          Uninstalling pip-19.2.3:
                Successfully uninstalled pip-19.2.3
                  Found existing installation: setuptools 41.2.0
                      Uninstalling setuptools-41.2.0:
                            Successfully uninstalled setuptools-41.2.0
                            Successfully installed pip-19.3.1 setuptools-42.0.2
                            Removing intermediate container af5738684a3e
                             ---> e6f3f4f35d32
Step 5/10 : RUN git clone -b sql-extended https://github.com/AvinashReddy3108/PaperplaneExtended /root/userbot
 ---> Running in 49844a5d4073
Cloning into '/root/userbot'...
fatal: Remote branch sql-extended not found in upstream origin
The command '/bin/sh -c git clone -b sql-extended https://github.com/AvinashReddy3108/PaperplaneExtended /root/userbot' returned a non-zero code: 128

**Comment by AvinashReddy3108** [comment]
Try deploying it now, I switched from docker to native dyno.

**Comment by sweetcock69** [comment]
Worked. Thanks :-)

**Comment by sweetcock69** [comment]
![Screenshot_20191215-164447__01](https://user-images.githubusercontent.com/50311435/70861917-bf95ba80-1f5a-11ea-9e3c-883e8ad002ae.jpg)
![Screenshot_20191215-164425__01](https://user-images.githubusercontent.com/50311435/70861918-c02e5100-1f5a-11ea-9237-c0c33ea79b22.jpg)
Bot becomes dead while using .aurl command. It was working fine 2 days ago.

**Comment by AvinashReddy3108** [comment]
Yes, my aria module are giving the memes right now.
Let's talk on Telegram: @AvinashReddy3108
