### ISSUE TITLE
Unable to Build w/ Cryptg Requirement

### ISSUE THREAD

**Issue by Bilibox** [AvinashReddy3108/PaperplaneExtended#45]
**Describe the bug**
When Cryptg is in requirements.txt the build always fails, removing cryptg from requirements allows it to build successfully 

**To Reproduce**
1. Build repo on heroku

**Expected behavior**
It should build correctly

**Python Version**
3.8.0

**Additional context**
Full code output here > https://pastebin.com/E8CCiUhk

**Comment by AvinashReddy3108** [comment]
Replaced `cryptg` with `tgcrypto`, deploys fine.
Closing this issue.
