### ISSUE TITLE
Urban Dictionary Gives Partial Description

### ISSUE THREAD

**Issue by Bilibox** [AvinashReddy3108/PaperplaneExtended#49]
**Describe the bug**
Urban Dictionary module cuts off part of the description

**To Reproduce**
.ud swag
Output >> 
Text: swag

Meaning: 1) The new generation's

Example: 
"That guy's got swag

**Expected behavior**
It should *at least* print the whole first line. if not at least the entire thing.

**Screenshots**
https://i.imgur.com/cnrBY6t.png

**Python Version**
3.8

**Comment by AvinashReddy3108** [comment]
Hmm, I noticed that issue myself a few days ago.
Should be solved by changing the library I use to scrape the UrbanDict.

**Comment by Bilibox** [comment]
Yeah the module has an issue open right now about it
https://github.com/novel/py-urbandict/issues/13

**Comment by AvinashReddy3108** [comment]
I switched to `asyncurban` as my new library of choice, works fine for me.
Closing this issue.
