### ISSUE TITLE
Aria and Download Functions

### ISSUE THREAD

**Issue by ghost** [AvinashReddy3108/PaperplaneExtended#8]
can you fix arias download from url function and add the ability to download from gdrive into download module

**Comment by a092devs** [comment]
Why would you need to download a certain thing from gdrive to download module? Please add more details!

**Comment by ghost** [comment]
for example, i have a gdrive link for a rom etc and i want to upload this in telegram servers, to do that i need to be able to download from gdrive, this is just one example ofc

**Comment by AvinashReddy3108** [comment]
> for example, i have a gdrive link for a rom etc and i want to upload this in telegram servers, to do that i need to be able to download from gdrive, this is just one example ofc

Generate a direct link using `.direct` and then `.aria url <URL>` to do it,
and then `.upload <FILE NAME>` to upload it to chat.

**Comment by HitaloM** [comment]
@AvinashReddy3108 pro af

**Comment by K-E-N-W-A-Y** [comment]
@AvinashReddy3108 it won't work. direct module crash for gdrive links

edit: ok i found it doesn't work for gdrive folder links but it works perfectly for gdrive file links
