### ISSUE TITLE
Lydia

### ISSUE THREAD

**Issue by ghost** [AvinashReddy3108/PaperplaneExtended#9]
Request for Lydia implementation. Iam ready with my API ;)

**Comment by a092devs** [comment]
@DAvinash97 lol! same

**Comment by E6883** [comment]
Star 5

**Comment by ghost** [comment]
Yeah that would be great

**Comment by AvinashReddy3108** [comment]
I don't want artificial intellignece to speak nonsense (even if it may seem funny for some.) on behalf of my profile, coz it may harm your reputation.
